import MuiTheme from '@/components/MuiTheme'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="pt-BR">
        <body className={inter.className}>
          <div className='h-full min-h-screen bg-slate-900 flex flex-col items-center justify-between'>
            <MuiTheme>
              {children}
              <span className='w-full h-full flex justify-end p-2 pr-4'>Desenvolvido por <a href='https://github.com/ViniciusCestarii' className='underline font-semibold ml-1' style={{color: 'rgba(180, 180, 240, 0.7)',}}>@ViniciusCestarii</a></span>
            </MuiTheme>
          </div>
        </body>
      </html>
  )
}
